chip_size_m: 76.8
crs: "EPSG:32619"
max_chips_per_request: 10000
db_path: "data/glooper.duckdb"
data_dir: "public/data"

# imagery_provider: static
imagery_provider: mass_orthos
# imagery_provider: cog
# imagery_provider_config:
#   cog_path: /path/to/imagery.tif
